### VARIABLES ###

@baseUrl = http://localhost:3000
@token = {{login.response.body.token}}
@refresh_token = {{login.response.body.refreshToken}}

### AUTHENTICATION ENDPOINTS ###

## 1. Create User (Public)
POST {{baseUrl}}/users
Content-Type: application/json

{
    "name": "Douglas",
    "email": "dougvil@msn.com",
    "password": "ABcd56!"
}
###

## 2. Login User (Public)
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "dougvil@msn.com",
    "password": "ABcd56!"
}
###


## 3. Refresh Token (Public)
POST  {{baseUrl}}/auth/refresh
Content-Type: application/json

{
    "refreshToken": "{{refresh_token}}"
}

###

POST {{baseUrl}}/home/sendEmail
Content-Type: application/json

{
    "to": "test@nestjs.com",
    "from": "noreply@nestjs.com",
    "subject": "Testing Nest MailerModule ✔",
    "text": "welcome",
    "html": "<b>welcome</b>"
}