import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialMigration1756863005569 implements MigrationInterface {
    name = 'InitialMigration1756863005569'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "plano" ("id" SERIAL NOT NULL, "nome" character varying(255) NOT NULL, "total_equipamento" character varying(4) NOT NULL DEFAULT '20', "integracao_whatsapp" boolean NOT NULL DEFAULT false, "integracao_sms" boolean NOT NULL DEFAULT false, "integracao_email" boolean NOT NULL DEFAULT false, "integracao_api" boolean NOT NULL DEFAULT true, "habilita_cliente" boolean NOT NULL DEFAULT false, "habilita_produto" boolean NOT NULL DEFAULT false, "habilita_botox" boolean NOT NULL DEFAULT false, "habilita_laudo" boolean NOT NULL DEFAULT false, "custo_sms" numeric(10,2) NOT NULL DEFAULT '0', "valor" numeric(10,2) NOT NULL DEFAULT '0', "valor_promo" numeric(10,2) NOT NULL DEFAULT '0', "valor_setor" numeric(10,2) NOT NULL DEFAULT '0', "valor_valor_profissional" numeric(10,2) NOT NULL DEFAULT '0', "soma_dias" integer NOT NULL DEFAULT '1', "bonus_dias" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2aaa50a32a3cedbf3a12708d8cf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "segmento" ("id" SERIAL NOT NULL, "nome" character varying(255) NOT NULL, "intervaloAlerta" integer NOT NULL DEFAULT '24', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0f5c538fc22bd6d5194d936f683" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tenancy" ("uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "segmento_id" integer, "prepago" boolean NOT NULL DEFAULT true, "slug" character varying(255) NOT NULL, "plano_id" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_644d5111fb5b1b1af41b3e0bec9" UNIQUE ("slug"), CONSTRAINT "PK_7d25d19c33f0e28849f335cf610" PRIMARY KEY ("uuid"))`);
        await queryRunner.query(`CREATE TABLE "users" ("uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "email" character varying(255) NOT NULL, "email_verified_at" TIMESTAMP, "password" character varying(255) NOT NULL, "remember_token" character varying(100), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_951b8f1dfc94ac1d0301a14b7e1" PRIMARY KEY ("uuid"))`);
        await queryRunner.query(`CREATE TABLE "status_financeiro" ("id" SERIAL NOT NULL, "tag" character varying(128) NOT NULL, "cor" character varying(7) NOT NULL DEFAULT '#000000', "menos_dias" character varying(3) NOT NULL DEFAULT '0', "mais_dias" character varying(3) NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_1337ca0735f4bae60b7bb948baa" UNIQUE ("tag"), CONSTRAINT "PK_90f592def90b7ad5d14cd657847" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."paciente_sexo_enum" AS ENUM('M', 'F', 'O')`);
        await queryRunner.query(`CREATE TABLE "paciente" ("uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "nome" character varying(128) NOT NULL, "cpf" character varying(16), "rg" character varying(16), "emissor" character varying(16), "emissor_uf" character varying(16), "celular" character varying(16), "nascimento" date, "sexo" "public"."paciente_sexo_enum" NOT NULL DEFAULT 'O', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_8eb9dba1cf8f89575da9a5cb6d4" UNIQUE ("cpf"), CONSTRAINT "PK_141cc4e130899f91c475bb4d6db" PRIMARY KEY ("uuid"))`);
        await queryRunner.query(`CREATE TABLE "profissional" ("uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "nome" character varying(128) NOT NULL, "conselho" character varying(32), "numero_conselho" character varying(32), "especialidade" character varying(64), "SomaTempoConsulta" character varying(32) NOT NULL, "tenancy_uuid" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_10e6f02ee202ece36bb804f6b22" PRIMARY KEY ("uuid"))`);
        await queryRunner.query(`CREATE TABLE "setor_profissional_tenancy" ("profissional_uuid" uuid NOT NULL, "setor_uuid" uuid NOT NULL, "tenancy_uuid" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d78724cafbf45c1112d1aca589d" PRIMARY KEY ("profissional_uuid", "setor_uuid", "tenancy_uuid"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d78724cafbf45c1112d1aca589" ON "setor_profissional_tenancy" ("profissional_uuid", "setor_uuid", "tenancy_uuid") `);
        await queryRunner.query(`CREATE TABLE "setor" ("uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenancy_uuid" uuid NOT NULL, "nome" character varying(255) NOT NULL, "ativo" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e00df9e84e62099c711c30de034" PRIMARY KEY ("uuid"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_eb6f6723bceee38c49ef825dad" ON "setor" ("tenancy_uuid", "nome") `);
        await queryRunner.query(`CREATE TABLE "grupoexame" ("uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "setor_id" uuid NOT NULL, "nome" character varying(255) NOT NULL, "detalhamento" character varying(255), "descricao" character varying(255), "previsao_tempo" character varying(255) NOT NULL DEFAULT 'horas', "previsao_laudo_tempo" character varying(255), "valor" numeric(10,2) NOT NULL DEFAULT '0', "tenancy_uuid" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "previsao_tempo_check" CHECK (previsao_tempo IN ('horas', 'dias')), CONSTRAINT "PK_3a4d6cff2bc302ce5c595e519b4" PRIMARY KEY ("uuid"))`);
        await queryRunner.query(`CREATE TABLE "exame" ("uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenancy_uuid" uuid NOT NULL, "setor_uuid" uuid NOT NULL, "paciente_uuid" uuid NOT NULL, "grupoexame_uuid" uuid NOT NULL, "profissional_uuid" uuid NOT NULL, "nome" character varying(255) NOT NULL, "data_exame" date, "horario_inicio_exame" TIME, "horario_fim_exame" TIME, "previsao_laudo" date, "laudo_nome_arquivo" character varying(175), "chave_acesso" character varying(32), "contra_chave" character varying(4), "valor" numeric(10,2) NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_1bffa9218f62c9802caace5e6bd" PRIMARY KEY ("uuid"))`);
        await queryRunner.query(`CREATE TABLE "procedimento" ("uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenancy_uuid" uuid NOT NULL, "nome" character varying(255) NOT NULL, "abreviacao" character varying(10), "TempoMedioMinutos" character varying(3), "valor" numeric(10,2) NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4c2d6dda930ae8e4c7563e2fc11" PRIMARY KEY ("uuid"))`);
        await queryRunner.query(`CREATE TABLE "agenda_procedimento_tenancy" ("agenda_uuid" uuid NOT NULL, "procedimento_uuid" uuid NOT NULL, "tenancy_uuid" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_520742b0ee7872d00ea773613e9" PRIMARY KEY ("agenda_uuid", "procedimento_uuid"))`);
        await queryRunner.query(`CREATE INDEX "IDX_677cd05619915c1116ba88bba8" ON "agenda_procedimento_tenancy" ("tenancy_uuid") `);
        await queryRunner.query(`CREATE INDEX "IDX_7d4f3ff28922895a2b187879a6" ON "agenda_procedimento_tenancy" ("procedimento_uuid") `);
        await queryRunner.query(`CREATE INDEX "IDX_1cae910fccb02317b52cb6cdfa" ON "agenda_procedimento_tenancy" ("agenda_uuid") `);
        await queryRunner.query(`CREATE TABLE "agenda" ("uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenancy_uuid" uuid NOT NULL, "paciente_uuid" uuid NOT NULL, "exame_uuid" uuid, "profissional_uuid" uuid NOT NULL, "data_consulta" date, "horario_inicio" TIME, "horario_fim" TIME, "recomendacao" character varying(175), "obs" character varying(175), "subtotal" numeric(10,2) NOT NULL DEFAULT '0', "desconto" numeric(10,2) NOT NULL DEFAULT '0', "recebido" numeric(10,2) NOT NULL DEFAULT '0', "saldo" numeric(10,2) NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_bd3f6f5a5d0b0ea93dc4bfd7dab" PRIMARY KEY ("uuid"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_555f8375fc6bc5adc94f1d367f" ON "agenda" ("profissional_uuid", "data_consulta", "horario_inicio") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b91f824c0a8d9cd2f9f59d268e" ON "agenda" ("paciente_uuid", "data_consulta", "horario_inicio") `);
        await queryRunner.query(`CREATE TABLE "solicitacao" ("agenda_uuid" uuid NOT NULL, "descricao" character varying(175) NOT NULL, CONSTRAINT "PK_926b78066afa6075851a7f09827" PRIMARY KEY ("agenda_uuid", "descricao"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f7c8adb8a1d25abc64d883331e" ON "solicitacao" ("descricao") `);
        await queryRunner.query(`CREATE INDEX "IDX_916b82b47dc0fffec738ccefd1" ON "solicitacao" ("agenda_uuid") `);
        await queryRunner.query(`CREATE TABLE "dominio" ("id" SERIAL NOT NULL, "tipo_dominio_id" integer NOT NULL, "nome" character varying(128) NOT NULL, "cor" character varying(6), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_aafd76b1c614e673172b22898ad" UNIQUE ("nome"), CONSTRAINT "PK_5a9f0a867f723e350086641bcd1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "paciente_log" ("users_uuid" uuid NOT NULL, "tenancy_uuid" uuid NOT NULL, "paciente_uuid" uuid NOT NULL, "DominioTipoAcesso_id" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fff70e99926b84e81f384aad70f" PRIMARY KEY ("users_uuid", "tenancy_uuid", "paciente_uuid", "DominioTipoAcesso_id"))`);
        await queryRunner.query(`CREATE TABLE "itens_financeiro" ("financeiro_uuid" uuid NOT NULL, "tenancy_uuid" uuid NOT NULL, "descricao" character varying(175) NOT NULL, "quantidade" numeric(5,2) NOT NULL, "valor_unit" numeric(10,2), "valor_total" numeric(10,2), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_f047bfde81b2f2ee3d4a0a8d2d0" PRIMARY KEY ("financeiro_uuid", "tenancy_uuid", "descricao"))`);
        await queryRunner.query(`CREATE TABLE "financeiro" ("uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenancy_uuid" uuid NOT NULL, "numero_sequencial" character varying(64) NOT NULL, "status_financeiro_id" integer NOT NULL, "valor_original" numeric(10,2) NOT NULL DEFAULT '0', "juros" numeric(10,2) NOT NULL DEFAULT '0', "multa" numeric(10,2) NOT NULL DEFAULT '0', "valor_pago" numeric(10,2) NOT NULL DEFAULT '0', "data_vencimento" date, "data_pagamento" date, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8de59cc86adccf987794c367b95" PRIMARY KEY ("uuid"))`);
        await queryRunner.query(`CREATE TABLE "tipo_dominio" ("id" SERIAL NOT NULL, "nome" character varying(128) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_2abce877e9c0c5e655f05268c40" UNIQUE ("nome"), CONSTRAINT "PK_439f6a4452ab6f5a9e719627a70" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "evento_financeiro" ("uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "status_financeiro_id" integer NOT NULL, "financeiro_uuid" uuid NOT NULL, "evento" character varying(128) NOT NULL, "nova_data" date, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_91c5e7722cdd5868557de94d40d" PRIMARY KEY ("uuid"))`);
        await queryRunner.query(`CREATE TABLE "tipo_dominio_config" ("id" SERIAL NOT NULL, "nome" character varying(128) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_6a781f73e9fb7997a2c8b53a20f" UNIQUE ("nome"), CONSTRAINT "PK_62a3303b14e9f6fcfbc85cf2cca" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "dominio_config" ("id" SERIAL NOT NULL, "tipodominio_config_id" integer NOT NULL, "nome" character varying(128) NOT NULL, "cor" character varying(6), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_26701cd6d7c8c16e3bb1bc8364d" UNIQUE ("nome"), CONSTRAINT "PK_01c8d03c9e6f57c7e82e9221830" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users_tenancy" ("users_uuid" uuid NOT NULL, "tenancy_uuid" uuid NOT NULL, CONSTRAINT "PK_45de2bd3d322a9691923f27238c" PRIMARY KEY ("users_uuid", "tenancy_uuid"))`);
        await queryRunner.query(`CREATE INDEX "IDX_35b23f0a0e956cd96f8001c8c9" ON "users_tenancy" ("users_uuid") `);
        await queryRunner.query(`CREATE INDEX "IDX_6e43ef5fdd6789e66fc0678bad" ON "users_tenancy" ("tenancy_uuid") `);
        await queryRunner.query(`CREATE TABLE "paciente_tenancy" ("paciente_uuid" uuid NOT NULL, "tenancy_uuid" uuid NOT NULL, CONSTRAINT "PK_b591f56f284d1dd877a3332950e" PRIMARY KEY ("paciente_uuid", "tenancy_uuid"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2695a5112018e99941f0658e49" ON "paciente_tenancy" ("paciente_uuid") `);
        await queryRunner.query(`CREATE INDEX "IDX_9dbb9de1ca7c066f3f5adfeb48" ON "paciente_tenancy" ("tenancy_uuid") `);
        await queryRunner.query(`ALTER TABLE "tenancy" ADD CONSTRAINT "FK_bb860834f706e7597aeb84bcb12" FOREIGN KEY ("plano_id") REFERENCES "plano"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenancy" ADD CONSTRAINT "FK_0a01480fc6b7d21c44165f56462" FOREIGN KEY ("segmento_id") REFERENCES "segmento"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "profissional" ADD CONSTRAINT "FK_8bbdf6372e71d737b89c2810599" FOREIGN KEY ("tenancy_uuid") REFERENCES "tenancy"("uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "setor_profissional_tenancy" ADD CONSTRAINT "FK_9f9155a4d70ff3f4c8f4e966753" FOREIGN KEY ("profissional_uuid") REFERENCES "profissional"("uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "setor_profissional_tenancy" ADD CONSTRAINT "FK_571f671bac788a1a74ecfec185a" FOREIGN KEY ("setor_uuid") REFERENCES "setor"("uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "setor_profissional_tenancy" ADD CONSTRAINT "FK_af8766f5c9b67a33f6cf3d1c33f" FOREIGN KEY ("tenancy_uuid") REFERENCES "tenancy"("uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "setor" ADD CONSTRAINT "FK_23efa7c033c24b96d5d1e1d8cd7" FOREIGN KEY ("tenancy_uuid") REFERENCES "tenancy"("uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "grupoexame" ADD CONSTRAINT "FK_e4ac687d7a7e71c248910b3a74b" FOREIGN KEY ("tenancy_uuid") REFERENCES "tenancy"("uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "grupoexame" ADD CONSTRAINT "FK_b22d73e9e265b95324a23daf7b9" FOREIGN KEY ("setor_id") REFERENCES "setor"("uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exame" ADD CONSTRAINT "FK_06d9e55fe8402534271e61bba36" FOREIGN KEY ("tenancy_uuid") REFERENCES "tenancy"("uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exame" ADD CONSTRAINT "FK_86bc9803db1f83ebe8b1d69ed12" FOREIGN KEY ("paciente_uuid") REFERENCES "paciente"("uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exame" ADD CONSTRAINT "FK_06ced19956adc2c53246d47751d" FOREIGN KEY ("profissional_uuid") REFERENCES "profissional"("uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exame" ADD CONSTRAINT "FK_2d38929b13f097900ab23c6dbac" FOREIGN KEY ("setor_uuid") REFERENCES "setor"("uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exame" ADD CONSTRAINT "FK_395ee538f35e9a98d207042451c" FOREIGN KEY ("grupoexame_uuid") REFERENCES "grupoexame"("uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "procedimento" ADD CONSTRAINT "FK_321f1ec4ba994eb2f0edc97df11" FOREIGN KEY ("tenancy_uuid") REFERENCES "tenancy"("uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agenda_procedimento_tenancy" ADD CONSTRAINT "FK_1cae910fccb02317b52cb6cdfa3" FOREIGN KEY ("agenda_uuid") REFERENCES "agenda"("uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agenda_procedimento_tenancy" ADD CONSTRAINT "FK_7d4f3ff28922895a2b187879a68" FOREIGN KEY ("procedimento_uuid") REFERENCES "procedimento"("uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agenda_procedimento_tenancy" ADD CONSTRAINT "FK_677cd05619915c1116ba88bba8d" FOREIGN KEY ("tenancy_uuid") REFERENCES "tenancy"("uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agenda" ADD CONSTRAINT "FK_3fb3a11b15c74b6b317e00a24b8" FOREIGN KEY ("tenancy_uuid") REFERENCES "tenancy"("uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agenda" ADD CONSTRAINT "FK_d952b7dea2f825f534a581d5248" FOREIGN KEY ("paciente_uuid") REFERENCES "paciente"("uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agenda" ADD CONSTRAINT "FK_effefc502cf904118221041869f" FOREIGN KEY ("exame_uuid") REFERENCES "exame"("uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agenda" ADD CONSTRAINT "FK_1adb5c63fb67c8bc4d3c39c28a2" FOREIGN KEY ("profissional_uuid") REFERENCES "profissional"("uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "solicitacao" ADD CONSTRAINT "FK_916b82b47dc0fffec738ccefd16" FOREIGN KEY ("agenda_uuid") REFERENCES "agenda"("uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dominio" ADD CONSTRAINT "FK_811434d75f340dc72d9e78d4cab" FOREIGN KEY ("tipo_dominio_id") REFERENCES "tipo_dominio"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "paciente_log" ADD CONSTRAINT "FK_e507d13307fb375f08a5a170fcb" FOREIGN KEY ("users_uuid") REFERENCES "users"("uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "paciente_log" ADD CONSTRAINT "FK_5134fd5335a7a0fe3ea4f54987e" FOREIGN KEY ("tenancy_uuid") REFERENCES "tenancy"("uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "paciente_log" ADD CONSTRAINT "FK_39122d1a6ce907f8325d8054f95" FOREIGN KEY ("paciente_uuid") REFERENCES "paciente"("uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "paciente_log" ADD CONSTRAINT "FK_94441060cac679e289be707fb22" FOREIGN KEY ("DominioTipoAcesso_id") REFERENCES "dominio"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "itens_financeiro" ADD CONSTRAINT "FK_37ffb57b7f90a6d18dd49d63af9" FOREIGN KEY ("financeiro_uuid") REFERENCES "financeiro"("uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "itens_financeiro" ADD CONSTRAINT "FK_10079f16d3909fda0566d2992c5" FOREIGN KEY ("tenancy_uuid") REFERENCES "tenancy"("uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "financeiro" ADD CONSTRAINT "FK_e58524408ead73f8508aa06a653" FOREIGN KEY ("tenancy_uuid") REFERENCES "tenancy"("uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "financeiro" ADD CONSTRAINT "FK_fc14c12c455ee48cfe062542ac6" FOREIGN KEY ("status_financeiro_id") REFERENCES "status_financeiro"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "evento_financeiro" ADD CONSTRAINT "FK_51ee79feba5ab3edc301426d5b6" FOREIGN KEY ("status_financeiro_id") REFERENCES "status_financeiro"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "evento_financeiro" ADD CONSTRAINT "FK_f3ec9771a9b2b0f0c79f4832a8b" FOREIGN KEY ("financeiro_uuid") REFERENCES "financeiro"("uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dominio_config" ADD CONSTRAINT "FK_11231a67645538585593be271e3" FOREIGN KEY ("tipodominio_config_id") REFERENCES "tipo_dominio_config"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users_tenancy" ADD CONSTRAINT "FK_35b23f0a0e956cd96f8001c8c9d" FOREIGN KEY ("users_uuid") REFERENCES "users"("uuid") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "users_tenancy" ADD CONSTRAINT "FK_6e43ef5fdd6789e66fc0678bad4" FOREIGN KEY ("tenancy_uuid") REFERENCES "tenancy"("uuid") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "paciente_tenancy" ADD CONSTRAINT "FK_2695a5112018e99941f0658e498" FOREIGN KEY ("paciente_uuid") REFERENCES "paciente"("uuid") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "paciente_tenancy" ADD CONSTRAINT "FK_9dbb9de1ca7c066f3f5adfeb480" FOREIGN KEY ("tenancy_uuid") REFERENCES "tenancy"("uuid") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "paciente_tenancy" DROP CONSTRAINT "FK_9dbb9de1ca7c066f3f5adfeb480"`);
        await queryRunner.query(`ALTER TABLE "paciente_tenancy" DROP CONSTRAINT "FK_2695a5112018e99941f0658e498"`);
        await queryRunner.query(`ALTER TABLE "users_tenancy" DROP CONSTRAINT "FK_6e43ef5fdd6789e66fc0678bad4"`);
        await queryRunner.query(`ALTER TABLE "users_tenancy" DROP CONSTRAINT "FK_35b23f0a0e956cd96f8001c8c9d"`);
        await queryRunner.query(`ALTER TABLE "dominio_config" DROP CONSTRAINT "FK_11231a67645538585593be271e3"`);
        await queryRunner.query(`ALTER TABLE "evento_financeiro" DROP CONSTRAINT "FK_f3ec9771a9b2b0f0c79f4832a8b"`);
        await queryRunner.query(`ALTER TABLE "evento_financeiro" DROP CONSTRAINT "FK_51ee79feba5ab3edc301426d5b6"`);
        await queryRunner.query(`ALTER TABLE "financeiro" DROP CONSTRAINT "FK_fc14c12c455ee48cfe062542ac6"`);
        await queryRunner.query(`ALTER TABLE "financeiro" DROP CONSTRAINT "FK_e58524408ead73f8508aa06a653"`);
        await queryRunner.query(`ALTER TABLE "itens_financeiro" DROP CONSTRAINT "FK_10079f16d3909fda0566d2992c5"`);
        await queryRunner.query(`ALTER TABLE "itens_financeiro" DROP CONSTRAINT "FK_37ffb57b7f90a6d18dd49d63af9"`);
        await queryRunner.query(`ALTER TABLE "paciente_log" DROP CONSTRAINT "FK_94441060cac679e289be707fb22"`);
        await queryRunner.query(`ALTER TABLE "paciente_log" DROP CONSTRAINT "FK_39122d1a6ce907f8325d8054f95"`);
        await queryRunner.query(`ALTER TABLE "paciente_log" DROP CONSTRAINT "FK_5134fd5335a7a0fe3ea4f54987e"`);
        await queryRunner.query(`ALTER TABLE "paciente_log" DROP CONSTRAINT "FK_e507d13307fb375f08a5a170fcb"`);
        await queryRunner.query(`ALTER TABLE "dominio" DROP CONSTRAINT "FK_811434d75f340dc72d9e78d4cab"`);
        await queryRunner.query(`ALTER TABLE "solicitacao" DROP CONSTRAINT "FK_916b82b47dc0fffec738ccefd16"`);
        await queryRunner.query(`ALTER TABLE "agenda" DROP CONSTRAINT "FK_1adb5c63fb67c8bc4d3c39c28a2"`);
        await queryRunner.query(`ALTER TABLE "agenda" DROP CONSTRAINT "FK_effefc502cf904118221041869f"`);
        await queryRunner.query(`ALTER TABLE "agenda" DROP CONSTRAINT "FK_d952b7dea2f825f534a581d5248"`);
        await queryRunner.query(`ALTER TABLE "agenda" DROP CONSTRAINT "FK_3fb3a11b15c74b6b317e00a24b8"`);
        await queryRunner.query(`ALTER TABLE "agenda_procedimento_tenancy" DROP CONSTRAINT "FK_677cd05619915c1116ba88bba8d"`);
        await queryRunner.query(`ALTER TABLE "agenda_procedimento_tenancy" DROP CONSTRAINT "FK_7d4f3ff28922895a2b187879a68"`);
        await queryRunner.query(`ALTER TABLE "agenda_procedimento_tenancy" DROP CONSTRAINT "FK_1cae910fccb02317b52cb6cdfa3"`);
        await queryRunner.query(`ALTER TABLE "procedimento" DROP CONSTRAINT "FK_321f1ec4ba994eb2f0edc97df11"`);
        await queryRunner.query(`ALTER TABLE "exame" DROP CONSTRAINT "FK_395ee538f35e9a98d207042451c"`);
        await queryRunner.query(`ALTER TABLE "exame" DROP CONSTRAINT "FK_2d38929b13f097900ab23c6dbac"`);
        await queryRunner.query(`ALTER TABLE "exame" DROP CONSTRAINT "FK_06ced19956adc2c53246d47751d"`);
        await queryRunner.query(`ALTER TABLE "exame" DROP CONSTRAINT "FK_86bc9803db1f83ebe8b1d69ed12"`);
        await queryRunner.query(`ALTER TABLE "exame" DROP CONSTRAINT "FK_06d9e55fe8402534271e61bba36"`);
        await queryRunner.query(`ALTER TABLE "grupoexame" DROP CONSTRAINT "FK_b22d73e9e265b95324a23daf7b9"`);
        await queryRunner.query(`ALTER TABLE "grupoexame" DROP CONSTRAINT "FK_e4ac687d7a7e71c248910b3a74b"`);
        await queryRunner.query(`ALTER TABLE "setor" DROP CONSTRAINT "FK_23efa7c033c24b96d5d1e1d8cd7"`);
        await queryRunner.query(`ALTER TABLE "setor_profissional_tenancy" DROP CONSTRAINT "FK_af8766f5c9b67a33f6cf3d1c33f"`);
        await queryRunner.query(`ALTER TABLE "setor_profissional_tenancy" DROP CONSTRAINT "FK_571f671bac788a1a74ecfec185a"`);
        await queryRunner.query(`ALTER TABLE "setor_profissional_tenancy" DROP CONSTRAINT "FK_9f9155a4d70ff3f4c8f4e966753"`);
        await queryRunner.query(`ALTER TABLE "profissional" DROP CONSTRAINT "FK_8bbdf6372e71d737b89c2810599"`);
        await queryRunner.query(`ALTER TABLE "tenancy" DROP CONSTRAINT "FK_0a01480fc6b7d21c44165f56462"`);
        await queryRunner.query(`ALTER TABLE "tenancy" DROP CONSTRAINT "FK_bb860834f706e7597aeb84bcb12"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9dbb9de1ca7c066f3f5adfeb48"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2695a5112018e99941f0658e49"`);
        await queryRunner.query(`DROP TABLE "paciente_tenancy"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6e43ef5fdd6789e66fc0678bad"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_35b23f0a0e956cd96f8001c8c9"`);
        await queryRunner.query(`DROP TABLE "users_tenancy"`);
        await queryRunner.query(`DROP TABLE "dominio_config"`);
        await queryRunner.query(`DROP TABLE "tipo_dominio_config"`);
        await queryRunner.query(`DROP TABLE "evento_financeiro"`);
        await queryRunner.query(`DROP TABLE "tipo_dominio"`);
        await queryRunner.query(`DROP TABLE "financeiro"`);
        await queryRunner.query(`DROP TABLE "itens_financeiro"`);
        await queryRunner.query(`DROP TABLE "paciente_log"`);
        await queryRunner.query(`DROP TABLE "dominio"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_916b82b47dc0fffec738ccefd1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f7c8adb8a1d25abc64d883331e"`);
        await queryRunner.query(`DROP TABLE "solicitacao"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b91f824c0a8d9cd2f9f59d268e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_555f8375fc6bc5adc94f1d367f"`);
        await queryRunner.query(`DROP TABLE "agenda"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1cae910fccb02317b52cb6cdfa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7d4f3ff28922895a2b187879a6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_677cd05619915c1116ba88bba8"`);
        await queryRunner.query(`DROP TABLE "agenda_procedimento_tenancy"`);
        await queryRunner.query(`DROP TABLE "procedimento"`);
        await queryRunner.query(`DROP TABLE "exame"`);
        await queryRunner.query(`DROP TABLE "grupoexame"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eb6f6723bceee38c49ef825dad"`);
        await queryRunner.query(`DROP TABLE "setor"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d78724cafbf45c1112d1aca589"`);
        await queryRunner.query(`DROP TABLE "setor_profissional_tenancy"`);
        await queryRunner.query(`DROP TABLE "profissional"`);
        await queryRunner.query(`DROP TABLE "paciente"`);
        await queryRunner.query(`DROP TYPE "public"."paciente_sexo_enum"`);
        await queryRunner.query(`DROP TABLE "status_financeiro"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "tenancy"`);
        await queryRunner.query(`DROP TABLE "segmento"`);
        await queryRunner.query(`DROP TABLE "plano"`);
    }

}
